server:
  port: 1888
  tomcat:
    accept-count: 1000
    max-connections: 20000
    threads:
      max: 1000
      min-spare: 100

spring:
  application:
    name: course-schedule-generation-system
  datasource:
    url: jdbc:mysql://localhost:3306/course_schedule_generation_system?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456